version: '2.3'
services:
  service:
    image: andimenge/movie-favs-frntnd:20f65d9c9562e81fc96a78928df9b1cbb38d7643
    init: true
    scale: 1
    labels:
      - "traefik.enable=true"
      - "traefik.backend=movie-favs-frntnd" # backend name
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:movies.andimenge.de"
      - "traefik.docker.network=loadbalancer"
    environment:
    - TZ=Europe/Berlin
    cpu_count: 1
    mem_reservation: 100m
    mem_limit: 1500000000
    restart: always
    networks:
    - loadbalancer

networks:
  loadbalancer:
    external: true
  